### ISSUE TITLE
Chrome extension's "Get CSS" always returns text 'undefined' below (on any html element)

### ISSUE THREAD

**Issue by rubyconvict** [krasimir/css-steal#2]
OS X 10.10.5, Chrome 45.0.2454.101 (64-bit), CSSSteal 1.0.1

**Comment by krasimir** [comment]
Thanks for reporting @rubyconvict I'll try reproducing it probably tonight.

**Comment by krasimir** [comment]
Hello @rubyconvict,

can you please open chrom://extensions and click on the `Update extensions` button. You should get 1.0.2 version and the problem should be solved. Let me know.

**Comment by rubyconvict** [comment]
Fixed.
